services:
  envoy:
    image: envoyproxy/envoy:v1.21-latest
    depends_on:
      - echo-server
    hostname: envoy
    ports:
      - "10000:10000"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
      - ../target/wasm32-wasi/release/envoy_rbi_filter.wasm:/etc/envoy/envoy_rbi_filter.wasm
    networks:
      - envoymesh

  echo-server:
    image: swaagie/echo-server:latest
    command: --body="<html><body></body></html>"
    hostname: echo_service
    networks:
      - envoymesh

networks:
  envoymesh: {}