services:
  envoy:
    image: envoyproxy/envoy:v1.21-latest
    depends_on:
      - echo-server
    hostname: envoy
    command: -l debug -c /etc/envoy/envoy.yaml
    ports:
      - "10000:10000"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
      # Use the release build in production
      - ../target/wasm32-wasi/debug/envoy_rbi_filter.wasm:/etc/envoy/envoy_rbi_filter.wasm
    networks:
      - envoymesh

  echo-server:
    image: swaagie/echo-server:latest
    command: -p 8080 -b '<html><body><!--#echo var=hello --></body></html>'
    hostname: echo_service
    networks:
      - envoymesh

networks:
  envoymesh: {}
