name: CI main
on:
  pull_request:
  push:
    branches:
      - main

env:
  RUST_BACKTRACE: 1

jobs:
  test:
    name: Cargo test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest] # windows-latest doesn't work atm
        rust: [stable, nightly]
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust }}
        components: rustfmt, clippy
    - name: Run cargo check
      uses: actions-rs/cargo@v1
      with:
        command: check
    - name: Run tests
      uses: actions-rs/cargo@v1
      with:
        command: test
    - name: Run clippy
      uses: actions-rs/cargo@v1
      with:
        command: clippy --all-targets --verbose
    - name: Verify code format
      uses: actions-rs/cargo@v1
      with:
        command: fmt --all -- --check